[env:esp32-s3-devkitc-1-n8r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200


; 1. NATIVE USB SETTINGS
build_flags = 
    ; Enable USB-CDC (Serial) on boot
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Set USB mode to Hardware CDC and JTAG
    -D ARDUINO_USB_MODE=1 

   
; 2. MEMORY SETTINGS FOR N8R8 (8MB Flash / 8MB PSRAM)
; "opi" is required for the 8MB PSRAM (Octal SPI)
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.prsim_type = opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
; monitor_dtr = 1
; monitor_rts = 1
lib_deps = 
    https://github.com/adafruit/Adafruit_LSM6DS.git
    adafruit/Adafruit NeoPixel @ ^1.12.0
    https://github.com/UravuLabs/MS5607.git
    https://github.com/adafruit/Adafruit_LIS3MDL.git